start_time: "09:00"
end_time: "17:00"
repeat: true
occurrences: 1
weekend: false

type:
  regular:
    link: link
    time: "regular"
    duration: "1 hour"
  lab:
    link: link
    time:
      mon: "11:00"
      tue: "15:00"
      wed:
        - "10:00"
        - "15:00"
    duration: "2 hours"
  elective:
    link: link
    time:
      thu: "12:00"
      fri: "09:00"
    duration: "1 hour"