[project]
name = "auto-zoom-meetings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jsonschema>=4.25.1",
    "pyinstaller>=6.16.0",
    "python-dotenv>=1.1.1",
    "schedule>=1.2.2",
]
